// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace buttons_Ios
{
	public partial class ViewController : UIViewController
	{
		public ViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
			//UIButton myButton = new UIButton(UIButtonType.System);
			
			myButton.Frame = new CGRect(25, 25, 300, 150);
			myButton.SetTitle("Hello, World!", UIControlState.Normal);
			
			myButton.SetTitleColor(UIColor.Green, UIControlState.Normal);
			myButton.SetTitleShadowColor(UIColor.Black, UIControlState.Normal);
			
			
			//var buttonTitle = "Hello, World!";
			//var normalAttributedTitle = new NSAttributedString(buttonTitle, foregroundColor: UIColor.Blue, strikethroughStyle: NSUnderlineStyle.Single);
			//myButton.SetAttributedTitle(normalAttributedTitle, UIControlState.Normal);
			
			//var buttonTitle = "Hello, World!";
			//var highlightedAttributedTitle = new NSAttributedString(buttonTitle, foregroundColor: UIColor.Green, strikethroughStyle: NSUnderlineStyle.Thick);
			//myButton.SetAttributedTitle(highlightedAttributedTitle, UIControlState.Highlighted);
			
			myButton.SetImage (UIImage.FromBundle ("Buttons/MagicWand.png"), UIControlState.Normal);
			//myButton.SetImage (UIImage.FromBundle ("Buttons/MagicWand_Highlight.png"), UIControlState.Highlighted);
			//myButton.SetImage (UIImage.FromBundle ("Buttons/MagicWand_On.png"), UIControlState.Selected);
			
			myButton.TouchUpInside += (sender, e) => {
				DoSomething();
			};
		}

		public void DoSomething()
		{
			Console.WriteLine("Button clicked!");
		}
	}
}
